PROJECT = web_api
PROJECT_DESCRIPTION = A web api for Chat Up!
PROJECT_VERSION = 0.1.0

LOCAL_DEPS = odbc eunit ssl sasl crypto runtime_tools
DEPS = cowboy adrenaline_db
dep_cowboy_commit = 2.6.3
dep_adrenaline_db = cp ${PWD}/../database_api/

DEP_PLUGINS = cowboy

include erlang.mk
