PROJECT = web_api
PROJECT_DESCRIPTION = A web api for Chat Up!
PROJECT_VERSION = 0.1.0
ERLC_OPTS = -Werror +debug_info +warn_export_vars +warn_shadow_vars +warn_obsolete_guard -I ../database_api/ebin

DEPS = cowboy
dep_cowboy_commit = 2.6.3

DEP_PLUGINS = cowboy

include erlang.mk
